package com.bom.domain.data.model;

import java.util.Date;

public class DatYearData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_year_data.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_year_data.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_year_data.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_year_data.cur_value
     *
     * @mbg.generated
     */
    private Double curValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_year_data.col_time
     *
     * @mbg.generated
     */
    private Date colTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_year_data.sys_time
     *
     * @mbg.generated
     */
    private Date sysTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_year_data.id
     *
     * @return the value of dat_year_data.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_year_data.id
     *
     * @param id the value for dat_year_data.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_year_data.project_id
     *
     * @return the value of dat_year_data.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_year_data.project_id
     *
     * @param projectId the value for dat_year_data.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_year_data.code
     *
     * @return the value of dat_year_data.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_year_data.code
     *
     * @param code the value for dat_year_data.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_year_data.cur_value
     *
     * @return the value of dat_year_data.cur_value
     *
     * @mbg.generated
     */
    public Double getCurValue() {
        return curValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_year_data.cur_value
     *
     * @param curValue the value for dat_year_data.cur_value
     *
     * @mbg.generated
     */
    public void setCurValue(Double curValue) {
        this.curValue = curValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_year_data.col_time
     *
     * @return the value of dat_year_data.col_time
     *
     * @mbg.generated
     */
    public Date getColTime() {
        return colTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_year_data.col_time
     *
     * @param colTime the value for dat_year_data.col_time
     *
     * @mbg.generated
     */
    public void setColTime(Date colTime) {
        this.colTime = colTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_year_data.sys_time
     *
     * @return the value of dat_year_data.sys_time
     *
     * @mbg.generated
     */
    public Date getSysTime() {
        return sysTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_year_data.sys_time
     *
     * @param sysTime the value for dat_year_data.sys_time
     *
     * @mbg.generated
     */
    public void setSysTime(Date sysTime) {
        this.sysTime = sysTime;
    }
}