package com.bom.domain.data.model;

import java.util.Date;

public class OptDataCol {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_data_col.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_data_col.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_data_col.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_data_col.cur_value
     *
     * @mbg.generated
     */
    private Double curValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_data_col.col_time
     *
     * @mbg.generated
     */
    private Date colTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_data_col.sys_time
     *
     * @mbg.generated
     */
    private Date sysTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_data_col.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_data_col.data_type
     *
     * @mbg.generated
     */
    private String dataType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_data_col.id
     *
     * @return the value of opt_data_col.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_data_col.id
     *
     * @param id the value for opt_data_col.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_data_col.project_id
     *
     * @return the value of opt_data_col.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_data_col.project_id
     *
     * @param projectId the value for opt_data_col.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_data_col.code
     *
     * @return the value of opt_data_col.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_data_col.code
     *
     * @param code the value for opt_data_col.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_data_col.cur_value
     *
     * @return the value of opt_data_col.cur_value
     *
     * @mbg.generated
     */
    public Double getCurValue() {
        return curValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_data_col.cur_value
     *
     * @param curValue the value for opt_data_col.cur_value
     *
     * @mbg.generated
     */
    public void setCurValue(Double curValue) {
        this.curValue = curValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_data_col.col_time
     *
     * @return the value of opt_data_col.col_time
     *
     * @mbg.generated
     */
    public Date getColTime() {
        return colTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_data_col.col_time
     *
     * @param colTime the value for opt_data_col.col_time
     *
     * @mbg.generated
     */
    public void setColTime(Date colTime) {
        this.colTime = colTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_data_col.sys_time
     *
     * @return the value of opt_data_col.sys_time
     *
     * @mbg.generated
     */
    public Date getSysTime() {
        return sysTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_data_col.sys_time
     *
     * @param sysTime the value for opt_data_col.sys_time
     *
     * @mbg.generated
     */
    public void setSysTime(Date sysTime) {
        this.sysTime = sysTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_data_col.quantity
     *
     * @return the value of opt_data_col.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_data_col.quantity
     *
     * @param quantity the value for opt_data_col.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_data_col.data_type
     *
     * @return the value of opt_data_col.data_type
     *
     * @mbg.generated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_data_col.data_type
     *
     * @param dataType the value for opt_data_col.data_type
     *
     * @mbg.generated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }
}