package com.bom.domain.data.model;

import java.util.Date;

public class OptStationCodes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_station_codes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_station_codes.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_station_codes.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_station_codes.code_des
     *
     * @mbg.generated
     */
    private String codeDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_station_codes.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_station_codes.param_name
     *
     * @mbg.generated
     */
    private String paramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_station_codes.param_name_des
     *
     * @mbg.generated
     */
    private String paramNameDes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_station_codes.id
     *
     * @return the value of opt_station_codes.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_station_codes.id
     *
     * @param id the value for opt_station_codes.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_station_codes.project_id
     *
     * @return the value of opt_station_codes.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_station_codes.project_id
     *
     * @param projectId the value for opt_station_codes.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_station_codes.code
     *
     * @return the value of opt_station_codes.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_station_codes.code
     *
     * @param code the value for opt_station_codes.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_station_codes.code_des
     *
     * @return the value of opt_station_codes.code_des
     *
     * @mbg.generated
     */
    public String getCodeDes() {
        return codeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_station_codes.code_des
     *
     * @param codeDes the value for opt_station_codes.code_des
     *
     * @mbg.generated
     */
    public void setCodeDes(String codeDes) {
        this.codeDes = codeDes == null ? null : codeDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_station_codes.create_date
     *
     * @return the value of opt_station_codes.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_station_codes.create_date
     *
     * @param createDate the value for opt_station_codes.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_station_codes.param_name
     *
     * @return the value of opt_station_codes.param_name
     *
     * @mbg.generated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_station_codes.param_name
     *
     * @param paramName the value for opt_station_codes.param_name
     *
     * @mbg.generated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_station_codes.param_name_des
     *
     * @return the value of opt_station_codes.param_name_des
     *
     * @mbg.generated
     */
    public String getParamNameDes() {
        return paramNameDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_station_codes.param_name_des
     *
     * @param paramNameDes the value for opt_station_codes.param_name_des
     *
     * @mbg.generated
     */
    public void setParamNameDes(String paramNameDes) {
        this.paramNameDes = paramNameDes == null ? null : paramNameDes.trim();
    }
}