package com.bom.domain.data.model;

import java.util.Date;

public class StationTop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_top.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_top.station_name
     *
     * @mbg.generated
     */
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_top.station_id
     *
     * @mbg.generated
     */
    private String stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_top.total_value
     *
     * @mbg.generated
     */
    private Double totalValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_top.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_top.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_top.id
     *
     * @return the value of station_top.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_top.id
     *
     * @param id the value for station_top.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_top.station_name
     *
     * @return the value of station_top.station_name
     *
     * @mbg.generated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_top.station_name
     *
     * @param stationName the value for station_top.station_name
     *
     * @mbg.generated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_top.station_id
     *
     * @return the value of station_top.station_id
     *
     * @mbg.generated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_top.station_id
     *
     * @param stationId the value for station_top.station_id
     *
     * @mbg.generated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_top.total_value
     *
     * @return the value of station_top.total_value
     *
     * @mbg.generated
     */
    public Double getTotalValue() {
        return totalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_top.total_value
     *
     * @param totalValue the value for station_top.total_value
     *
     * @mbg.generated
     */
    public void setTotalValue(Double totalValue) {
        this.totalValue = totalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_top.type
     *
     * @return the value of station_top.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_top.type
     *
     * @param type the value for station_top.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_top.create_date
     *
     * @return the value of station_top.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_top.create_date
     *
     * @param createDate the value for station_top.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}