package com.bom.domain.data.model;

import java.util.Date;

public class StationCodes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_codes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_codes.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_codes.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_codes.code_des
     *
     * @mbg.generated
     */
    private String codeDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_codes.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_codes.id
     *
     * @return the value of station_codes.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_codes.id
     *
     * @param id the value for station_codes.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_codes.project_id
     *
     * @return the value of station_codes.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_codes.project_id
     *
     * @param projectId the value for station_codes.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_codes.code
     *
     * @return the value of station_codes.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_codes.code
     *
     * @param code the value for station_codes.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_codes.code_des
     *
     * @return the value of station_codes.code_des
     *
     * @mbg.generated
     */
    public String getCodeDes() {
        return codeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_codes.code_des
     *
     * @param codeDes the value for station_codes.code_des
     *
     * @mbg.generated
     */
    public void setCodeDes(String codeDes) {
        this.codeDes = codeDes == null ? null : codeDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_codes.create_date
     *
     * @return the value of station_codes.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_codes.create_date
     *
     * @param createDate the value for station_codes.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}