package com.bom.domain.spvdata.model;

import java.util.Date;

public class BasEquInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.equ_id
     *
     * @mbg.generated
     */
    private Integer equId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.station_id
     *
     * @mbg.generated
     */
    private String stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.equ_name
     *
     * @mbg.generated
     */
    private String equName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.equ_name_EN
     *
     * @mbg.generated
     */
    private String equNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.equ_no
     *
     * @mbg.generated
     */
    private String equNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.specification
     *
     * @mbg.generated
     */
    private String specification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.company_code
     *
     * @mbg.generated
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.project_code
     *
     * @mbg.generated
     */
    private String projectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.kks_code
     *
     * @mbg.generated
     */
    private String kksCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.equ_category_big
     *
     * @mbg.generated
     */
    private Integer equCategoryBig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.equ_category_small
     *
     * @mbg.generated
     */
    private Integer equCategorySmall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.manufacture_date
     *
     * @mbg.generated
     */
    private Date manufactureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.amount
     *
     * @mbg.generated
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.protect_level
     *
     * @mbg.generated
     */
    private String protectLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.belongsystem
     *
     * @mbg.generated
     */
    private Integer belongsystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.sp_id
     *
     * @mbg.generated
     */
    private Integer spId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.files_id
     *
     * @mbg.generated
     */
    private String filesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.gateway_id
     *
     * @mbg.generated
     */
    private Integer gatewayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.device_no
     *
     * @mbg.generated
     */
    private String deviceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.equ_grad
     *
     * @mbg.generated
     */
    private String equGrad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.equ_status
     *
     * @mbg.generated
     */
    private String equStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_equ_info.equ_desc
     *
     * @mbg.generated
     */
    private String equDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.equ_id
     *
     * @return the value of bas_equ_info.equ_id
     *
     * @mbg.generated
     */
    public Integer getEquId() {
        return equId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.equ_id
     *
     * @param equId the value for bas_equ_info.equ_id
     *
     * @mbg.generated
     */
    public void setEquId(Integer equId) {
        this.equId = equId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.station_id
     *
     * @return the value of bas_equ_info.station_id
     *
     * @mbg.generated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.station_id
     *
     * @param stationId the value for bas_equ_info.station_id
     *
     * @mbg.generated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.equ_name
     *
     * @return the value of bas_equ_info.equ_name
     *
     * @mbg.generated
     */
    public String getEquName() {
        return equName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.equ_name
     *
     * @param equName the value for bas_equ_info.equ_name
     *
     * @mbg.generated
     */
    public void setEquName(String equName) {
        this.equName = equName == null ? null : equName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.equ_name_EN
     *
     * @return the value of bas_equ_info.equ_name_EN
     *
     * @mbg.generated
     */
    public String getEquNameEn() {
        return equNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.equ_name_EN
     *
     * @param equNameEn the value for bas_equ_info.equ_name_EN
     *
     * @mbg.generated
     */
    public void setEquNameEn(String equNameEn) {
        this.equNameEn = equNameEn == null ? null : equNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.equ_no
     *
     * @return the value of bas_equ_info.equ_no
     *
     * @mbg.generated
     */
    public String getEquNo() {
        return equNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.equ_no
     *
     * @param equNo the value for bas_equ_info.equ_no
     *
     * @mbg.generated
     */
    public void setEquNo(String equNo) {
        this.equNo = equNo == null ? null : equNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.specification
     *
     * @return the value of bas_equ_info.specification
     *
     * @mbg.generated
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.specification
     *
     * @param specification the value for bas_equ_info.specification
     *
     * @mbg.generated
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.company_code
     *
     * @return the value of bas_equ_info.company_code
     *
     * @mbg.generated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.company_code
     *
     * @param companyCode the value for bas_equ_info.company_code
     *
     * @mbg.generated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.project_code
     *
     * @return the value of bas_equ_info.project_code
     *
     * @mbg.generated
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.project_code
     *
     * @param projectCode the value for bas_equ_info.project_code
     *
     * @mbg.generated
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode == null ? null : projectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.kks_code
     *
     * @return the value of bas_equ_info.kks_code
     *
     * @mbg.generated
     */
    public String getKksCode() {
        return kksCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.kks_code
     *
     * @param kksCode the value for bas_equ_info.kks_code
     *
     * @mbg.generated
     */
    public void setKksCode(String kksCode) {
        this.kksCode = kksCode == null ? null : kksCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.equ_category_big
     *
     * @return the value of bas_equ_info.equ_category_big
     *
     * @mbg.generated
     */
    public Integer getEquCategoryBig() {
        return equCategoryBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.equ_category_big
     *
     * @param equCategoryBig the value for bas_equ_info.equ_category_big
     *
     * @mbg.generated
     */
    public void setEquCategoryBig(Integer equCategoryBig) {
        this.equCategoryBig = equCategoryBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.equ_category_small
     *
     * @return the value of bas_equ_info.equ_category_small
     *
     * @mbg.generated
     */
    public Integer getEquCategorySmall() {
        return equCategorySmall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.equ_category_small
     *
     * @param equCategorySmall the value for bas_equ_info.equ_category_small
     *
     * @mbg.generated
     */
    public void setEquCategorySmall(Integer equCategorySmall) {
        this.equCategorySmall = equCategorySmall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.manufacture_date
     *
     * @return the value of bas_equ_info.manufacture_date
     *
     * @mbg.generated
     */
    public Date getManufactureDate() {
        return manufactureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.manufacture_date
     *
     * @param manufactureDate the value for bas_equ_info.manufacture_date
     *
     * @mbg.generated
     */
    public void setManufactureDate(Date manufactureDate) {
        this.manufactureDate = manufactureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.amount
     *
     * @return the value of bas_equ_info.amount
     *
     * @mbg.generated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.amount
     *
     * @param amount the value for bas_equ_info.amount
     *
     * @mbg.generated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.unit
     *
     * @return the value of bas_equ_info.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.unit
     *
     * @param unit the value for bas_equ_info.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.protect_level
     *
     * @return the value of bas_equ_info.protect_level
     *
     * @mbg.generated
     */
    public String getProtectLevel() {
        return protectLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.protect_level
     *
     * @param protectLevel the value for bas_equ_info.protect_level
     *
     * @mbg.generated
     */
    public void setProtectLevel(String protectLevel) {
        this.protectLevel = protectLevel == null ? null : protectLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.belongsystem
     *
     * @return the value of bas_equ_info.belongsystem
     *
     * @mbg.generated
     */
    public Integer getBelongsystem() {
        return belongsystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.belongsystem
     *
     * @param belongsystem the value for bas_equ_info.belongsystem
     *
     * @mbg.generated
     */
    public void setBelongsystem(Integer belongsystem) {
        this.belongsystem = belongsystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.sp_id
     *
     * @return the value of bas_equ_info.sp_id
     *
     * @mbg.generated
     */
    public Integer getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.sp_id
     *
     * @param spId the value for bas_equ_info.sp_id
     *
     * @mbg.generated
     */
    public void setSpId(Integer spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.files_id
     *
     * @return the value of bas_equ_info.files_id
     *
     * @mbg.generated
     */
    public String getFilesId() {
        return filesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.files_id
     *
     * @param filesId the value for bas_equ_info.files_id
     *
     * @mbg.generated
     */
    public void setFilesId(String filesId) {
        this.filesId = filesId == null ? null : filesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.gateway_id
     *
     * @return the value of bas_equ_info.gateway_id
     *
     * @mbg.generated
     */
    public Integer getGatewayId() {
        return gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.gateway_id
     *
     * @param gatewayId the value for bas_equ_info.gateway_id
     *
     * @mbg.generated
     */
    public void setGatewayId(Integer gatewayId) {
        this.gatewayId = gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.device_no
     *
     * @return the value of bas_equ_info.device_no
     *
     * @mbg.generated
     */
    public String getDeviceNo() {
        return deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.device_no
     *
     * @param deviceNo the value for bas_equ_info.device_no
     *
     * @mbg.generated
     */
    public void setDeviceNo(String deviceNo) {
        this.deviceNo = deviceNo == null ? null : deviceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.equ_grad
     *
     * @return the value of bas_equ_info.equ_grad
     *
     * @mbg.generated
     */
    public String getEquGrad() {
        return equGrad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.equ_grad
     *
     * @param equGrad the value for bas_equ_info.equ_grad
     *
     * @mbg.generated
     */
    public void setEquGrad(String equGrad) {
        this.equGrad = equGrad == null ? null : equGrad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.equ_status
     *
     * @return the value of bas_equ_info.equ_status
     *
     * @mbg.generated
     */
    public String getEquStatus() {
        return equStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.equ_status
     *
     * @param equStatus the value for bas_equ_info.equ_status
     *
     * @mbg.generated
     */
    public void setEquStatus(String equStatus) {
        this.equStatus = equStatus == null ? null : equStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_equ_info.equ_desc
     *
     * @return the value of bas_equ_info.equ_desc
     *
     * @mbg.generated
     */
    public String getEquDesc() {
        return equDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_equ_info.equ_desc
     *
     * @param equDesc the value for bas_equ_info.equ_desc
     *
     * @mbg.generated
     */
    public void setEquDesc(String equDesc) {
        this.equDesc = equDesc == null ? null : equDesc.trim();
    }
}