package com.bom.domain.spvdata.model;

import java.math.BigDecimal;

public class PubStationInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.station_id
     *
     * @mbg.generated
     */
    private String stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.station_lat
     *
     * @mbg.generated
     */
    private BigDecimal stationLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.station_lng
     *
     * @mbg.generated
     */
    private BigDecimal stationLng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.station_name
     *
     * @mbg.generated
     */
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.station_name_en
     *
     * @mbg.generated
     */
    private String stationNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.station_esp
     *
     * @mbg.generated
     */
    private String stationEsp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.file_id
     *
     * @mbg.generated
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.connect_time
     *
     * @mbg.generated
     */
    private String connectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.station_state
     *
     * @mbg.generated
     */
    private Short stationState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.station_level
     *
     * @mbg.generated
     */
    private Float stationLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_station_info.station_type
     *
     * @mbg.generated
     */
    private String stationType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.id
     *
     * @return the value of pub_station_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.id
     *
     * @param id the value for pub_station_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.station_id
     *
     * @return the value of pub_station_info.station_id
     *
     * @mbg.generated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.station_id
     *
     * @param stationId the value for pub_station_info.station_id
     *
     * @mbg.generated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.station_lat
     *
     * @return the value of pub_station_info.station_lat
     *
     * @mbg.generated
     */
    public BigDecimal getStationLat() {
        return stationLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.station_lat
     *
     * @param stationLat the value for pub_station_info.station_lat
     *
     * @mbg.generated
     */
    public void setStationLat(BigDecimal stationLat) {
        this.stationLat = stationLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.station_lng
     *
     * @return the value of pub_station_info.station_lng
     *
     * @mbg.generated
     */
    public BigDecimal getStationLng() {
        return stationLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.station_lng
     *
     * @param stationLng the value for pub_station_info.station_lng
     *
     * @mbg.generated
     */
    public void setStationLng(BigDecimal stationLng) {
        this.stationLng = stationLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.station_name
     *
     * @return the value of pub_station_info.station_name
     *
     * @mbg.generated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.station_name
     *
     * @param stationName the value for pub_station_info.station_name
     *
     * @mbg.generated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.station_name_en
     *
     * @return the value of pub_station_info.station_name_en
     *
     * @mbg.generated
     */
    public String getStationNameEn() {
        return stationNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.station_name_en
     *
     * @param stationNameEn the value for pub_station_info.station_name_en
     *
     * @mbg.generated
     */
    public void setStationNameEn(String stationNameEn) {
        this.stationNameEn = stationNameEn == null ? null : stationNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.station_esp
     *
     * @return the value of pub_station_info.station_esp
     *
     * @mbg.generated
     */
    public String getStationEsp() {
        return stationEsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.station_esp
     *
     * @param stationEsp the value for pub_station_info.station_esp
     *
     * @mbg.generated
     */
    public void setStationEsp(String stationEsp) {
        this.stationEsp = stationEsp == null ? null : stationEsp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.location
     *
     * @return the value of pub_station_info.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.location
     *
     * @param location the value for pub_station_info.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.addr
     *
     * @return the value of pub_station_info.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.addr
     *
     * @param addr the value for pub_station_info.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.file_id
     *
     * @return the value of pub_station_info.file_id
     *
     * @mbg.generated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.file_id
     *
     * @param fileId the value for pub_station_info.file_id
     *
     * @mbg.generated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.connect_time
     *
     * @return the value of pub_station_info.connect_time
     *
     * @mbg.generated
     */
    public String getConnectTime() {
        return connectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.connect_time
     *
     * @param connectTime the value for pub_station_info.connect_time
     *
     * @mbg.generated
     */
    public void setConnectTime(String connectTime) {
        this.connectTime = connectTime == null ? null : connectTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.station_state
     *
     * @return the value of pub_station_info.station_state
     *
     * @mbg.generated
     */
    public Short getStationState() {
        return stationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.station_state
     *
     * @param stationState the value for pub_station_info.station_state
     *
     * @mbg.generated
     */
    public void setStationState(Short stationState) {
        this.stationState = stationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.station_level
     *
     * @return the value of pub_station_info.station_level
     *
     * @mbg.generated
     */
    public Float getStationLevel() {
        return stationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.station_level
     *
     * @param stationLevel the value for pub_station_info.station_level
     *
     * @mbg.generated
     */
    public void setStationLevel(Float stationLevel) {
        this.stationLevel = stationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_station_info.station_type
     *
     * @return the value of pub_station_info.station_type
     *
     * @mbg.generated
     */
    public String getStationType() {
        return stationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_station_info.station_type
     *
     * @param stationType the value for pub_station_info.station_type
     *
     * @mbg.generated
     */
    public void setStationType(String stationType) {
        this.stationType = stationType == null ? null : stationType.trim();
    }
}