package com.bom.domain;

import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Created by jindb on 2017/7/28.
 *
 * @author: jindb
 * @date: 2017/7/28 11:17
 * @description:
 */
@Service
public interface IService<T> {
    T selectByKey(Object key);

    int save(T entity);

    int delete(Object key);

    int updateAll(T entity);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    List<T> selectAll();
//    int updateNotNull(T entity);
//
//    List<T> selectByExample(Object example);
}
