package com.bom.domain;

import java.util.List;

/**
 * Created by jindb on 2017/7/28.
 *
 * @author: jindb
 * @date: 2017/7/28 11:25
 * @description:
 */
public interface Mapper<T> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Object key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    T selectByPrimaryKey(Object key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    List<T> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(T record);
}
