package com.bom.domain.mix.model;

public class Func {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.cal_code
     *
     * @mbg.generated
     */
    private String calCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.cal_code_name
     *
     * @mbg.generated
     */
    private String calCodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.list_var
     *
     * @mbg.generated
     */
    private String listVar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.function
     *
     * @mbg.generated
     */
    private String function;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.func_desc
     *
     * @mbg.generated
     */
    private String funcDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.unit_id
     *
     * @mbg.generated
     */
    private Integer unitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.id
     *
     * @return the value of func.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.id
     *
     * @param id the value for func.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.project_id
     *
     * @return the value of func.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.project_id
     *
     * @param projectId the value for func.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.cal_code
     *
     * @return the value of func.cal_code
     *
     * @mbg.generated
     */
    public String getCalCode() {
        return calCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.cal_code
     *
     * @param calCode the value for func.cal_code
     *
     * @mbg.generated
     */
    public void setCalCode(String calCode) {
        this.calCode = calCode == null ? null : calCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.cal_code_name
     *
     * @return the value of func.cal_code_name
     *
     * @mbg.generated
     */
    public String getCalCodeName() {
        return calCodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.cal_code_name
     *
     * @param calCodeName the value for func.cal_code_name
     *
     * @mbg.generated
     */
    public void setCalCodeName(String calCodeName) {
        this.calCodeName = calCodeName == null ? null : calCodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.list_var
     *
     * @return the value of func.list_var
     *
     * @mbg.generated
     */
    public String getListVar() {
        return listVar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.list_var
     *
     * @param listVar the value for func.list_var
     *
     * @mbg.generated
     */
    public void setListVar(String listVar) {
        this.listVar = listVar == null ? null : listVar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.function
     *
     * @return the value of func.function
     *
     * @mbg.generated
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.function
     *
     * @param function the value for func.function
     *
     * @mbg.generated
     */
    public void setFunction(String function) {
        this.function = function == null ? null : function.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.func_desc
     *
     * @return the value of func.func_desc
     *
     * @mbg.generated
     */
    public String getFuncDesc() {
        return funcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.func_desc
     *
     * @param funcDesc the value for func.func_desc
     *
     * @mbg.generated
     */
    public void setFuncDesc(String funcDesc) {
        this.funcDesc = funcDesc == null ? null : funcDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.unit_id
     *
     * @return the value of func.unit_id
     *
     * @mbg.generated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.unit_id
     *
     * @param unitId the value for func.unit_id
     *
     * @mbg.generated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
}