package com.bom.domain.mix.model;

public class Reference {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference.project_id
     *
     * @mbg.generated
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference.ref_code
     *
     * @mbg.generated
     */
    private String refCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference.ref_code_name
     *
     * @mbg.generated
     */
    private String refCodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference.ref_value
     *
     * @mbg.generated
     */
    private Double refValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference.ref_desc
     *
     * @mbg.generated
     */
    private String refDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference.unit_id
     *
     * @mbg.generated
     */
    private Integer unitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference.id
     *
     * @return the value of reference.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference.id
     *
     * @param id the value for reference.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference.project_id
     *
     * @return the value of reference.project_id
     *
     * @mbg.generated
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference.project_id
     *
     * @param projectId the value for reference.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference.ref_code
     *
     * @return the value of reference.ref_code
     *
     * @mbg.generated
     */
    public String getRefCode() {
        return refCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference.ref_code
     *
     * @param refCode the value for reference.ref_code
     *
     * @mbg.generated
     */
    public void setRefCode(String refCode) {
        this.refCode = refCode == null ? null : refCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference.ref_code_name
     *
     * @return the value of reference.ref_code_name
     *
     * @mbg.generated
     */
    public String getRefCodeName() {
        return refCodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference.ref_code_name
     *
     * @param refCodeName the value for reference.ref_code_name
     *
     * @mbg.generated
     */
    public void setRefCodeName(String refCodeName) {
        this.refCodeName = refCodeName == null ? null : refCodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference.ref_value
     *
     * @return the value of reference.ref_value
     *
     * @mbg.generated
     */
    public Double getRefValue() {
        return refValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference.ref_value
     *
     * @param refValue the value for reference.ref_value
     *
     * @mbg.generated
     */
    public void setRefValue(Double refValue) {
        this.refValue = refValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference.ref_desc
     *
     * @return the value of reference.ref_desc
     *
     * @mbg.generated
     */
    public String getRefDesc() {
        return refDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference.ref_desc
     *
     * @param refDesc the value for reference.ref_desc
     *
     * @mbg.generated
     */
    public void setRefDesc(String refDesc) {
        this.refDesc = refDesc == null ? null : refDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference.unit_id
     *
     * @return the value of reference.unit_id
     *
     * @mbg.generated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference.unit_id
     *
     * @param unitId the value for reference.unit_id
     *
     * @mbg.generated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
}